name: Translation Check

on:
  pull_request:
    branches: 
      - main
    paths:
      - "**locales**/*.json"

jobs:
  check-translations:
    name: Check and update translations
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all files including changes
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: "**locales**/*.json"

      - name: Check if translation files have changed
        id: check-changes
        run: |
          if [ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]; then
            echo "Translation files have been changed"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changed_files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "No translation files changed"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run translation update
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: davidparys/nuxt-translation-open-ai-deepl@v1.0.0
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          root-directory: ${{ inputs.root-directory || 'deepl-translator-vue-i18n/example' }}
          source-locale: ${{ inputs.source-locale || 'en' }}
          target-locales: ${{ inputs.target-locales || 'de,fr,es,pl' }}
          openai-model: ${{ inputs.openai-model || 'gpt-3.5-turbo' }}
          formality-level: ${{ inputs.formality-level }}

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        id: commit-changes
        run: |
          # Check if there are any changes to commit
          if [[ -z $(git status --porcelain) ]]; then
            echo "No translation changes to commit"
            echo "has_translation_changes=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Committing translation changes directly to PR branch"
            git add -A
            git commit -m "Update translations for locales files"
            git push
            echo "has_translation_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### Translation Update
            
            I've detected changes to localization files in this PR and automatically updated translations.
            
            ${{ steps.commit-changes.outputs.has_translation_changes == 'true' && 'Translations have been updated and pushed directly to this PR branch.' || 'No translation changes were needed.' }}
            
            Changed files:
            ```
            ${{ steps.changed-files.outputs.changed_files }}
            ```
          comment_tag: translation-check 